### ISSUE TITLE
No such file or directory: 'PF_embeddings.npy'

### ISSUE THREAD

**Issue by SeekPoint** [BUAAQingYuan/SDP-Attention_CNN_relation_classification#1]
mldl@ub1604:~/ub16_prj/SDP-Attention_CNN_relation_classification$ python3 relation_cnn_static_sdp.py 
Traceback (most recent call last):
  File "relation_cnn_static_sdp.py", line 6, in <module>
    import load_data_weight
  File "/home/mldl/ub16_prj/SDP-Attention_CNN_relation_classification/load_data_weight.py", line 15, in <module>
    PF_embeddings = numpy.load('PF_embeddings.npy')
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'PF_embeddings.npy'
mldl@ub1604:~/ub16_prj/SDP-Attention_CNN_relation_classification$

**Comment by QqqingYuan** [comment]
> mldl@ub1604:/ub16_prj/SDP-Attention_CNN_relation_classification$ python3 relation_cnn_static_sdp.py
> Traceback (most recent call last):
> File "relation_cnn_static_sdp.py", line 6, in 
> import load_data_weight
> File "/home/mldl/ub16_prj/SDP-Attention_CNN_relation_classification/load_data_weight.py", line 15, in 
> PF_embeddings = numpy.load('PF_embeddings.npy')
> File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 384, in load
> fid = open(file, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'PF_embeddings.npy'
> mldl@ub1604:/ub16_prj/SDP-Attention_CNN_relation_classification$

hi~，PF ，such Position Feature is from paper  “Relation classification via convolutional deep neural network”，which is just initialization randomly and is ok.  In my experiments, the dimension is matter。hope helpful to u.
